import swaggerAutogen from "swagger-autogen";
import { uuidv4 } from "zod";

const doc = {
  info: {
    title: "RAC API",
    description: "API Documentation generated by swagger-autogen",
    version: "1.0.0",
  },
  host: "localhost:8000",
  basePath: "/",
  schemes: ["http"],
  securityDefinitions: {
    bearerAuth: {
      type: "apiKey",
      in: "header",
      name: "Authorization",
      description:
        "Enter your bearer token in the format **Bearer &lt;token>**",
    },
  },
};

const uniqueId = new Date().toISOString().replace(/[:.]/g, "-");
const outputFile = `../../swagger-${uniqueId}.json`;

// Pointing to server.ts because all endpoints are mounted there.
const endpointsFiles = ["../server.ts"];

// Generate swagger.json
swaggerAutogen()(outputFile, endpointsFiles, doc).then(() => {
  console.log(
    "📄 Swagger documentation generated successfully at src/swagger.json!",
  );
});
